# Part 2: SQL and Database

## Import and Load

In [1]:
%load_ext google.cloud.bigquery

In [2]:
import os
import pandas as pd
from google.cloud import bigquery
import google.auth
from google.cloud import bigquery

In [3]:
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'aqueous-freedom-398208-cfe0d4e567f2.json'

In [6]:
bigquery_client = bigquery.Client()

DefaultCredentialsError: File aqueous-freedom-398208-cfe0d4e567f2.json was not found.

## Tabel Customer

In [ ]:
query1 = """
    CREATE TABLE `aqueous-freedom-398208.OFD_Team_1.Customer`(
        id_customer INT64 NOT NULL,
        name STRING NOT NULL,
        registration_date DATE NOT NULL,
        contact STRING,
    );
"""
result1 = bigquery_client.query(query1)

In [ ]:
query2 = """
    insert into `aqueous-freedom-398208.OFD_Team_1.Customer`
    values
        (1, 'Fadhli', '2023-11-01', '7834'),
        (2, 'Ridho', '2023-11-02', '2956'),
        (3, 'Syaikh', '2023-11-03', '6412'),
        (4, 'Fine', '2023-11-04', '5078'),
        (5, 'Dika', '2023-11-05', '1239'),
        (6, 'Beri', '2023-11-06', '8645'),
        (7, 'Budi', '2023-11-07', '3091'),
        (8, 'Badu', '2023-11-08', '5726'),
        (9, 'Coki', '2023-11-09', '1863'),
        (10, 'David', '2023-11-10', '9542'),
        (11, 'Danu', '2023-11-11', '4276'),
        (12, 'Dodi', '2023-11-12', '5081'),
        (13, 'Dedi', '2023-11-13', '7392'),
        (14, 'Endang', '2023-11-14', '6158'),
        (15, 'Eric', '2023-11-15', '2947'),
        (16, 'Eti', '2023-11-16', '8304'),
        (17, 'Fahri', '2023-11-17', '1625'),
        (18, 'Fahmi', '2023-11-18', '4957'),
        (19, 'Farhan', '2023-11-19', '2316'),
        (20, 'Faishal', '2023-11-20', '9674'),
        (21, 'Fauzan', '2023-11-21', '5409'),
        (22, 'Geri', '2023-11-22', '3816'),
        (23, 'Harun', '2023-11-23', '6942'),
        (24, 'Heru', '2023-11-24', '1785'),
        (25, 'Haris', '2023-11-25', '4632'),
        (26, 'Iwan', '2023-11-26', '8025'),
        (27, 'Inul', '2023-11-27', '5493'),
        (28, 'Ivan', '2023-11-28', '5493'),
        (29, 'Jeri', '2023-11-29', '8274'),
        (30, 'Jamal', '2023-11-30', '6048');
        """

result2 = bigquery_client.query(query2)

## Tabel Order

In [ ]:
query3 = """
    CREATE TABLE `aqueous-freedom-398208.OFD_Team_1.Order`(
        id_order INT64 NOT NULL,
        fk_customer_id INT64 NOT NULL,
        order_date DATE NOT NULL,
        fk_food_id INT64 NOT NULL,
        quantity INT64 NOT NULL,
        status STRING NOT NULL,
    );
"""
result3 = bigquery_client.query(query3)

In [5]:
query4 = """
    insert into `aqueous-freedom-398208.OFD_Team_1.Order`
    values
        (1, 14, '2023-11-01', 4, 2, 'sukses'),
        (2, 12, '2023-11-02', 7, 2, 'sukses'),
        (3, 26, '2023-11-03', 2, 3, 'sukses'),
        (4, 7, '2023-11-04', 7, 2, 'pending'),
        (5, 29, '2023-11-05', 2, 2, 'sukses'),
        (6, 23, '2023-11-06', 6, 1, 'pending'),
        (7, 8, '2023-11-07', 4, 1, 'pending'),
        (8, 20, '2023-11-08', 7, 3, 'sukses'),
        (9, 28, '2023-11-09', 5, 2, 'sukses'),
        (10, 3, '2023-11-10', 2, 1, 'sukses'),
        (11, 27, '2023-11-11', 3, 1, 'pending'),
        (12, 15, '2023-11-12', 7, 4, 'pending'),
        (13, 23, '2023-11-13', 1, 4, 'pending'),
        (14, 5, '2023-11-14', 7, 3, 'pending'),
        (15, 7, '2023-11-15', 1, 2, 'sukses'),
        (16, 25, '2023-11-16', 3, 2, 'pending'),
        (17, 20, '2023-11-17', 5, 3, 'sukses'),
        (18, 3, '2023-11-18', 3, 1, 'sukses'),
        (19, 22, '2023-11-19', 4, 1, 'pending'),
        (20, 16, '2023-11-20', 7, 1, 'pending'),
        (21, 12, '2023-11-21', 2, 2, 'sukses'),
        (22, 27, '2023-11-22', 4, 2, 'sukses'),
        (23, 25, '2023-11-23', 1, 2, 'pending'),
        (24, 19, '2023-11-24', 6, 3, 'sukses'),
        (25, 9, '2023-11-25', 5, 4, 'pending'),
        (26, 18, '2023-11-26', 1, 3, 'sukses'),
        (27, 23, '2023-11-27', 4, 2, 'sukses'),
        (28, 22, '2023-11-28', 3, 2, 'sukses'),
        (29, 11, '2023-11-29', 7, 1, 'pending'),
        (30, 27, '2023-11-30', 6, 3, 'pending'),

        (31, 6, '2023-12-01', 4, 2, 'sukses'),
        (32, 17, '2023-12-02', 7, 2, 'sukses'),
        (33, 18, '2023-12-03', 3, 3, 'sukses'),
        (34, 16, '2023-12-04', 5, 2, 'pending'),
        (35, 24, '2023-12-05', 3, 2, 'sukses'),
        (36, 11, '2023-12-06', 7, 1, 'pending'),
        (37, 8, '2023-12-07', 1, 1, 'pending'),
        (38, 10, '2023-12-08', 2, 3, 'sukses'),
        (39, 13, '2023-12-09', 5, 2, 'sukses'),
        (40, 19, '2023-12-10', 3, 1, 'sukses'),
        (41, 14, '2023-12-11', 6, 1, 'pending'),
        (42, 28, '2023-12-12', 4, 4, 'pending'),
        (43, 28, '2023-12-13', 5, 4, 'pending'),
        (44, 29, '2023-12-14', 3, 3, 'pending'),
        (45, 15, '2023-12-15', 6, 2, 'sukses'),
        (46, 14, '2023-12-16', 1, 2, 'pending'),
        (47, 9, '2023-12-17', 5, 3, 'sukses'),
        (48, 2, '2023-12-18', 3, 1, 'sukses'),
        (49, 20, '2023-12-19', 7, 1, 'pending'),
        (50, 26, '2023-12-20', 2, 1, 'pending'),
        (51, 30, '2023-12-21', 6, 2, 'sukses'),
        (52, 28, '2023-12-22', 5, 2, 'sukses'),
        (53, 17, '2023-12-23', 4, 2, 'pending'),
        (54, 4, '2023-12-24', 1, 3, 'sukses'),
        (55, 5, '2023-12-25', 7, 4, 'pending'),
        (56, 22, '2023-12-26', 2, 3, 'sukses'),
        (57, 20, '2023-12-27', 3, 2, 'sukses'),
        (58, 29, '2023-12-28', 4, 2, 'sukses'),
        (59, 16, '2023-12-29', 6, 1, 'pending'),
        (60, 1, '2023-12-30', 5, 3, 'pending'),
        (61, 5, '2023-12-31', 6, 1, 'sukses'),

        (62, 21, '2024-01-01', 5, 2, 'sukses'),
        (63, 6, '2024-01-02', 1, 2, 'sukses'),
        (64, 25, '2024-01-03', 3, 3, 'sukses'),
        (65, 28, '2024-01-04', 2, 2, 'pending'),
        (66, 19, '2024-01-05', 5, 2, 'sukses'),
        (67, 15, '2024-01-06', 4, 1, 'pending'),
        (68, 12, '2024-01-07', 7, 1, 'pending'),
        (69, 14, '2024-01-08', 1, 3, 'sukses'),
        (70, 7, '2024-01-09', 7, 2, 'sukses'),
        (71, 25, '2024-01-10', 2, 1, 'sukses'),
        (72, 11, '2024-01-11', 3, 1, 'pending'),
        (73, 1, '2024-01-12', 5, 4, 'pending'),
        (74, 3, '2024-01-13', 1, 4, 'pending'),
        (75, 13, '2024-01-14', 4, 3, 'pending'),
        (76, 26, '2024-01-15', 6, 2, 'sukses'),
        (77, 6, '2024-01-16', 3, 2, 'pending'),
        (78, 16, '2024-01-17', 1, 3, 'sukses'),
        (79, 17, '2024-01-18', 5, 1, 'sukses'),
        (80, 29, '2024-01-19', 6, 1, 'pending'),
        (81, 15, '2024-01-20', 4, 1, 'pending'),
        (82, 8, '2024-01-21', 7, 2, 'sukses'),
        (83, 23, '2024-01-22', 5, 2, 'sukses'),
        (84, 21, '2024-01-23', 2, 2, 'pending'),
        (85, 25, '2024-01-24', 1, 3, 'sukses'),
        (86, 30, '2024-01-25', 4, 4, 'pending'),
        (87, 14, '2024-01-26', 7, 3, 'sukses'),
        (88, 24, '2024-01-27', 3, 2, 'sukses'),
        (89, 4, '2024-01-28', 6, 2, 'sukses'),
        (90, 13, '2024-01-29', 1, 1, 'pending'),
        (91, 7, '2024-01-30', 3, 3, 'pending'),
        (92, 9, '2024-01-31', 7, 2, 'sukses')
        ;
        """

result4 = bigquery_client.query(query4)

NameError: name 'bigquery_client' is not defined

## Tabel Food

In [ ]:
query5 = """
    CREATE TABLE `aqueous-freedom-398208.OFD_Team_1.Food`(
        id_food INT64 NOT NULL,
        food_name STRING NOT NULL,
        fk_resto_id INT64 NOT NULL,
        price INT64 NOT NULL,
    );
"""
result5 = bigquery_client.query(query5)

In [ ]:
query6 = """
    insert into `aqueous-freedom-398208.OFD_Team_1.Food`
    values
        (1, 'Nasi Goreng', 1, 25000),
        (2, 'Ayam Bakar', 1, 35000),
        (3, 'Soto Ayam', 2, 30000),
        (4, 'Bakso', 3, 18000),
        (5, 'Mie Goreng', 4, 20000),
        (6, 'Sate Ayam', 3, 25000),
        (7, 'Pecel Lele', 4, 18000);
    """

result6 = bigquery_client.query(query6)

## Tabel Restaurant

In [ ]:
query7 = """
    CREATE TABLE `aqueous-freedom-398208.OFD_Team_1.Restaurant`(
        id_restaurant INT64 NOT NULL,
        restaurant_name STRING NOT NULL,
        city STRING NOT NULL,
    );
"""
result7 = bigquery_client.query(query7)

In [ ]:
query8 = """
    insert into `aqueous-freedom-398208.OFD_Team_1.Restaurant`
    values
        (1, 'Ambar Resto', 'Jakarta Barat'),
        (2, 'Bunda Resto', 'Jakarta Timur'),
        (3, 'Cak Resto', 'Surabaya'),
        (4, 'Mang Asep Resto', 'Bandung')
        ;
    """

result8 = bigquery_client.query(query8)

## 1. Berapa banyak customer yang registrasi di platform setiap harinya?

In [ ]:
query9 = """
    SELECT
        registration_date,
        COUNT(id_customer) AS Jumlah_Customer_Regristrasi
    FROM `aqueous-freedom-398208.OFD_Team_1.Customer`
    GROUP BY registration_date
    ORDER BY registration_date ASC;
"""

result9 = bigquery_client.query(query9)
df9 = result9.to_dataframe()
df9

   registration_date  Jumlah_Customer_Regristrasi
0         2023-11-01                            1
1         2023-11-02                            1
2         2023-11-03                            1
3         2023-11-04                            1
4         2023-11-05                            1
5         2023-11-06                            1
6         2023-11-07                            1
7         2023-11-08                            1
8         2023-11-09                            1
9         2023-11-10                            1
10        2023-11-11                            1
11        2023-11-12                            1
12        2023-11-13                            1
13        2023-11-14                            1
14        2023-11-15                            1
15        2023-11-16                            1
16        2023-11-17                            1
17        2023-11-18                            1
18        2023-11-19                            1
19        2023-11-20                            1
20        2023-11-21                            1
21        2023-11-22                            1
22        2023-11-23                            1
23        2023-11-24                            1
24        2023-11-25                            1
25        2023-11-26                            1
26        2023-11-27                            1
27        2023-11-28                            1
28        2023-11-29                            1
29        2023-11-30                            1

## 2. Berapa banyak jumlah order yang terbentuk setiap harinya?

In [ ]:
query10 = """
    SELECT
        order_date,
        COUNT(id_order) AS Jumlah_Order
    FROM `aqueous-freedom-398208.OFD_Team_1.Order`
    GROUP BY order_date
    ORDER BY order_date ASC;
"""

result10 = bigquery_client.query(query10)
df10 = result10.to_dataframe()
df10

    order_date  Jumlah_Order
0   2023-11-01             1
1   2023-11-02             1
2   2023-11-03             1
3   2023-11-04             1
4   2023-11-05             1
..         ...           ...
87  2024-01-27             1
88  2024-01-28             1
89  2024-01-29             1
90  2024-01-30             1
91  2024-01-31             1

[92 rows x 2 columns]

## 3. Berapa keuntungan yang didapat dari OK! Food Delivery setiap harinya?

In [ ]:
query11 = """
    SELECT
        o.order_date AS Tanggal,
        SUM(o.quantity * f.price) AS Keuntungan
    FROM `aqueous-freedom-398208.OFD_Team_1.Order` o
    INNER JOIN `aqueous-freedom-398208.OFD_Team_1.Food` f ON o.fk_food_id = f.id_food
    GROUP BY o.order_date
    ORDER BY o.order_date ASC;
"""

result11 = bigquery_client.query(query11)
df11 = result11.to_dataframe()
df11

       Tanggal  Keuntungan
0   2023-11-01       36000
1   2023-11-02       36000
2   2023-11-03      105000
3   2023-11-04       36000
4   2023-11-05       70000
..         ...         ...
87  2024-01-27       60000
88  2024-01-28       50000
89  2024-01-29       25000
90  2024-01-30       90000
91  2024-01-31       36000

[92 rows x 2 columns]

## 4. Berapa average spending 1 orang customer setiap harinya dalam 1 bulan?

In [ ]:
query12 = """
WITH MonthlyTransactions AS (
    SELECT
        DATE_TRUNC(o.order_date, MONTH) AS bulan,
        o.fk_customer_id,
        COUNT(*) AS jumlah_transaksi
    FROM `aqueous-freedom-398208.OFD_Team_1.Order` o
    GROUP BY bulan, o.fk_customer_id
),
MonthlyExpenditures AS (
    SELECT
        DATE_TRUNC(o.order_date, MONTH) AS bulan,
        o.fk_customer_id,
        SUM(f.price * o.quantity) AS total_pengeluaran
    FROM  `aqueous-freedom-398208.OFD_Team_1.Order` o
    JOIN  `aqueous-freedom-398208.OFD_Team_1.Food` f ON o.fk_food_id = f.id_food
    GROUP BY
        bulan, o.fk_customer_id
),
CustomerData AS (
    SELECT
        c.id_customer,
        c.name AS nama_customer
    FROM
        `aqueous-freedom-398208.OFD_Team_1.Customer` c
)

SELECT
    cd.nama_customer,
    mt.bulan AS Bulan,
    COALESCE(ROUND(me.total_pengeluaran / mt.jumlah_transaksi, 2), 0) AS rata_rata_pengeluaran_per_transaksi
FROM
    MonthlyTransactions mt
LEFT JOIN
    MonthlyExpenditures me ON mt.bulan = me.bulan AND mt.fk_customer_id = me.fk_customer_id
JOIN
    CustomerData cd ON mt.fk_customer_id = cd.id_customer
ORDER BY
    Bulan ASC, cd.nama_customer ASC;

"""

result12 = bigquery_client.query(query12)
df12 = result12.to_dataframe()
df12

   nama_customer       Bulan  rata_rata_pengeluaran_per_transaksi
0           Badu  2023-11-01                              18000.0
1           Budi  2023-11-01                              43000.0
2           Coki  2023-11-01                              80000.0
3           Danu  2023-11-01                              18000.0
4           Dika  2023-11-01                              54000.0
..           ...         ...                                  ...
61          Ivan  2024-01-01                              70000.0
62          Iwan  2024-01-01                              50000.0
63         Jamal  2024-01-01                              72000.0
64          Jeri  2024-01-01                              25000.0
65        Syaikh  2024-01-01                             100000.0

[66 rows x 3 columns]